[project]
name = "funresource"
version = "1.0.55"
description = "funresource"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "bs4>=0.0.2", "feedparser>=6.0.11", "funddb>=1.2.11", "funshell>=1.0.19", "funutil>=1.0.43", "funsecret>=1.4.83", "sqlalchemy>=2.0.36", "tqdm>=4.67.1",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[project.scripts]
funresource = "funresource.run:funresource"

[dependency-groups]
dev = [ "funbuild>=1.6.65",]

[tool.setuptools]
license-files = []
